# Generated by Django 3.2 on 2023-05-30 00:54

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20230529_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesproyecto',
            name='fecha_visita',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 30))]),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 30), message='La fecha debe ser igual o posterior a 30-05-2023.')]),
        ),
    ]
