# Generated by Django 3.2 on 2023-05-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_auto_20230529_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.DeleteModel(
            name='DetallesProyecto',
        ),
    ]
