# Generated by Django 3.2 on 2023-05-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_auto_20230530_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(),
        ),
    ]
