# Generated by Django 3.2 on 2023-06-01 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_alter_proyecto_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='estados',
            new_name='estado',
        ),
    ]
