# Generated by Django 3.2 on 2023-06-06 16:34

import direcciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0002_alter_departamento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='direccion',
            field=models.CharField(error_messages={'unique': 'La dirección ya existe. Ingresa una dirección diferente.'}, max_length=100, validators=[direcciones.models.validate_direction]),
        ),
    ]
