# Generated by Django 3.2 on 2023-06-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0003_alter_direccion_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
