# Generated by Django 3.2 on 2023-05-30 13:00

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tecnicos', '0001_initial'),
        ('proyectos', '0004_auto_20230530_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 30), message='La fecha debe ser igual o posterior a 30-05-2023.')])),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(max_length=500)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
                ('tecnicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecnicos.tecnico')),
            ],
            options={
                'verbose_name': 'Visita técnica',
                'verbose_name_plural': 'Visitas técnicas',
            },
        ),
    ]
