# Generated by Django 3.2 on 2023-06-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_tecnicas', '0003_alter_visitatecnica_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitatecnica',
            old_name='tecnicos',
            new_name='tecnico',
        ),
    ]
