# Generated by Django 3.2 on 2023-06-19 20:30

from django.db import migrations, models
import materiales.models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[materiales.models.validate_valor]),
        ),
    ]
