# Generated by Django 3.2 on 2023-05-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_alter_detallecotizacion_total_pagar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecotizacion',
            name='total_pagar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
