# Generated by Django 3.2 on 2023-05-30 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_auto_20230529_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='detallecotizacion',
            options={'verbose_name': 'Detalle de cotización', 'verbose_name_plural': 'Detalle de cotizaciones'},
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='cantidad',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
