# Generated by Django 3.2 on 2023-06-19 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0007_auto_20230529_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='descuento',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15)]),
        ),
    ]
